### ISSUE TITLE
Sportdigital EDGE HD

### ISSUE THREAD

**Issue by ghost** [picons/picons#2233]
# SNP/SRP entries

**snp.index**
```
sportdigitaledgehd=sportdigitaledgehd
sportdigitaledge=sportdigitaledgehd
edgesporthd=sportdigitaledgehd

```
[sportdigitaledgehd.default.png.zip](https://github.com/user-attachments/files/15934869/sportdigitaledgehd.default.png.zip)

```

**Comment by AbuBaniaz** [comment]
We already have this logo.
https://github.com/picons/picons/blob/master/build-source/logos/sportdigitaledge.default.svg

I can't see the difference to the one you are uploading. Can you please explain the difference/change to the logo.

**Comment by ghost** [comment]
Der Sender Name EDGE Sport und das Logo hat sich geändert, aber bei mir kommt mit Sportdigital EDGE kein Logo mehr.

**Comment by AbuBaniaz** [comment]
What is different between our logo (what already exists on our repository) and your logo (what you attached)?

Was ist der Unterschied zwischen unserem Logo (das bereits in unserem Repository vorhanden ist) und Ihrem Logo (das Sie angehängt haben)?

**Comment by ghost** [comment]
Aber es kommt kein Logo… Von meinem iPhone gesendetAm 23.06.2024 um 22:31 schrieb AbuBaniaz ***@***.***>:﻿
What is different between our logo (what already exists on our repository) and your logo (what you attached)?
Was ist der Unterschied zwischen unserem Logo (das bereits in unserem Repository vorhanden ist) und Ihrem Logo (das Sie angehängt haben)?

**Comment by AbuBaniaz** [comment]
We do have the logo. I posted the link to the logo we have. Click on it and then tell me what is different to the logo you are uploading.

Wir haben das Logo. Ich habe den Link zu unserem Logo gepostet. Klicken Sie darauf und sagen Sie mir dann, was sich von dem Logo unterscheidet, das Sie hochladen.

**Comment by ghost** [comment]
Ja das Logo ist gleich, ja es auf GitHub da, aber es kommt kein Logo wenn ich auf Astra 19.2 oder IPTV auf dem Sender schalte.Von meinem iPhone gesendetAm 23.06.2024 um 22:37 schrieb AbuBaniaz ***@***.***>:﻿
We do have the logo. I posted the link to the logo we have. Click on it and then tell me what is different to the logo you are uploading.
Wir haben das Logo. Ich habe den Link zu unserem Logo gepostet. Klicken Sie darauf und sagen Sie mir dann, was sich von dem Logo unterscheidet, das Sie hochladen.

**Comment by AbuBaniaz** [comment]
The picons on this project are created from this repository/github. Do you think we are accessing your receiver to create them?

We have said this to you before. more than once.
logo on repository/github + link on repository/github = Picon created

If a picon on your receiver is not created it is either because:
1. We don't have the logo on repository/github
2. We don't have required link on repository/github
3. We don't have logo and link on repository/github

So for your issue, all we needed were the links. I added them here:
https://github.com/AbuBaniaz/picons/commit/fa50a9721fcb5ffc46e9f8d67b3845fb954c7ce6

As far as I am concerned this issue is resolved.  Please try the latest picon pack.

**Comment by Lexzie** [comment]
He just wanted that we add the link, although I doubt if we should add
`edgesporthd=sportdigitaledgehd`
Maybe somewhere Edge Sport still exists?

**Comment by AbuBaniaz** [comment]
We can remove any links later if needed.

If he wanted us to just add the link, why upload logos? They were identical to what you added, he even changed the names of the logo.

**Comment by Lexzie** [comment]
The only reason I can think of is that he has trouble to understand how we work...
I assume it is not on purpose.

**Comment by AbuBaniaz** [comment]
We have explained it to him many times. If he doesn't understand, we can reword it and consider adapting the instructions for everyone.

He has never asked for clarification. I assume he is doing it deliberately. Like raising more than 10 issues in a short while.
