### ISSUE TITLE
Danish picons

### ISSUE THREAD

**Issue by Mette590** [picons/picons#2431]
# SNP/SRP entries

**snp.index**
```
TV 2 | Danmark HD (Syd)=TV2dk2023.png
TV 2 Echo=TV2Echo2023..png
Kanal 5=kanal5dk2024.png
TV3 SPORT=tv3sportdk2004.png

```

_Make sure you replace the above sample data with the actual data you want added._

# Logos

```
[logos.zip](https://github.com/user-attachments/files/17689869/logos.zip)

```

Attach a `zip` file containing the logos, properly named according to the channelname used in `snp.index` or `srp.index`.

**PS: Make sure to read [CONTRIBUTING.md](https://github.com/picons/picons/blob/master/CONTRIBUTING.md)**

**Comment by TheLegoBatman** [comment]
Those logos already exist in this repo. Which frequencies are missing?

**Comment by Mette590** [comment]
I'm using DVB-C. Du you want the the frequencies of the channels?

TV 2 | Danmark HD (Syd) and TV2 Echo has no logo and Kanal 5 and TV3 sport has the wrong logo.

**Comment by TheLegoBatman** [comment]
Send us your channel list (bouquets) with lamedb included.

**Comment by Mette590** [comment]
I hope this is the right file otherwise let me know.
[channels.zip](https://github.com/user-attachments/files/17691784/channels.zip)

**Comment by TheLegoBatman** [comment]
I've fixed those. It seems there are more missing etc. Can you take a look tomorrow then come back here and add what's missing or wrong.

More specifically these attached 
[danish.zip](https://github.com/user-attachments/files/17692194/danish.zip)

Here are the picons built only with the list you sent us
[piconsdanish.zip](https://github.com/user-attachments/files/17692230/piconsdanish.zip)

**Comment by Mette590** [comment]
I have tried to update my Openvix with this command but the icons did not get updated:

wget https://feed.openpicons.com/install.sh -O /tmp/openpicons.sh; sh /tmp/openpicons.sh; rm -f /tmp/openpicons.sh;

**Comment by TheLegoBatman** [comment]
You have installed a feed. Go to your plugins and install the latest picons from there, or figure out how to manually copy them to your box using ftp.

**Comment by AbuBaniaz** [comment]
Did you want the SRP versions updated too?

**Comment by Mette590** [comment]
I have installed the latest picons from the plugins but the icons it is still not updated. What are the SRP versions?

**Comment by AbuBaniaz** [comment]
SRP ones are by service reference. Let's  leave those for now until the snp ones are sorted.

Which version and date did you install?

**Comment by Mette590** [comment]
I installed the snp_full.220x132-190x102.dark.on.transparent (2024-11-10--16.30)

**Comment by AbuBaniaz** [comment]
These are still the missing ones
[missing-picons-all_services.csv](https://github.com/user-attachments/files/17709958/missing-picons-all_services.csv)


For the ones with the "wrong logo", the way we work with snp is that if you have different channels (but same name), we use the service reference. You can see that in the commit by legobatman. Please  list them in a chart with the service reference and the logo that is on this repository. Here is a list of the found ones if it helps start you off.
[found-picons.csv](https://github.com/user-attachments/files/17709972/found-picons.csv)

**Comment by AbuBaniaz** [comment]
I think the `kanal 5` wrong logo issue was fixed.
![Screenshot 2024-11-12 020834](https://github.com/user-attachments/assets/ffda785a-65d9-4cbc-bde2-8fc14ec63822)

I have added some more links here, please advise if any are incorrect.
https://github.com/picons/picons/pull/2433

There are  a few for which I dont think we have logos. Your attachment did not load, so please re-upload any missing logos.

**Comment by Mette590** [comment]
Here is the logos zip file again.

[logos.zip](https://github.com/user-attachments/files/17710344/logos.zip)

**Comment by AbuBaniaz** [comment]
kanal5, the linkage was corrected

tv2, we have this logo already. Do we need to update it?
https://github.com/picons/picons/blob/master/build-source/logos/tv2-pistohicra.default.svg

tv2echo, we have this already
https://github.com/picons/picons/blob/master/build-source/logos/tv2echo.default.svg

**Comment by Mette590** [comment]
TV2: the logo in my zip file is the latest version. 
Tv2echo logo: no need to update.

**Comment by TheLegoBatman** [comment]
Don't add any to the srp index for now since it only takes one command to sort them out unless you feel like doing all manually.

**Comment by Lexzie** [comment]
I added a few more links and a logo, I hope that is okay.
Can you help identify these channels with a link to a website or screenshot of the logos:
```
Ekstrakanalen
ESC/ESC1
Lukket ESports TV
Norlyskanalen
Stofa Event
```

Is TV 2 | Danmark HD (Syd) not the same as TV Syd?
https://www.tvsyd.dk/
https://logos.fandom.com/wiki/TV_Syd
The same for TV 2 | Danmark HD (Østjylland).
https://logos.fandom.com/wiki/TV2_%C3%98stjylland
https://www.tv2ostjylland.dk/

So should they get the `tv2-pistohicra` logo or `tv2syd` and `tv2ostjylland`?

**Comment by Mette590** [comment]
Ekstrakanalen, ESC/ESC1, Lukket ESports TV, Norlyskanalen, Stofa Event are not real channels with a logo. They are closed, information or event channels. I don't know what ESC/ESC1 is never heard of it before and it is encrypted so I can't see it.

TV 2 | Danmark HD (Syd) is not the same as TV Syd and TV 2 | Danmark HD (Østjylland) is not the same as tv2 østjylland.
TV 2 | Danmark HD (Syd) and TV 2 | Danmark HD (Østjylland) should have the TV2dk2023.png logo in my zip file with logos.
TV syd the tv2syd logo and tv2 østjylland the tv2ostjylland.

**Comment by Lexzie** [comment]
> Ekstrakanalen, ESC/ESC1, Lukket ESports TV, Norlyskanalen, Stofa Event are not real channels with a logo. They are closed, information or event channels. I don't know what ESC/ESC1 is never heard of it before and it is encrypted so I can't see it.
> 
> TV 2 | Danmark HD (Syd) is not the same as TV Syd and TV 2 | Danmark HD (Østjylland) is not the same as tv2 østjylland. TV 2 | Danmark HD (Syd) and TV 2 | Danmark HD (Østjylland) should have the TV2dk2023.png logo in my zip file with logos. TV syd the tv2syd logo and tv2 østjylland the tv2ostjylland.

Allright, so then I think all logos are present now.
Let us know if a logo is missing or wrong.

**Comment by Mette590** [comment]
All the icons are now updated. Thanks for the help.
